### ISSUE TITLE
facebook share button not reading my site's meta og tags

### ISSUE THREAD

**Issue by geekyme** [hugesuccess/facebook-sdk#3]
Hi, 

I'm very new to facebook api. I just used the facebook-share handlebars helper and supplied a url. Upon clicking it a nice popup appear but it doesn't display titles, description and picture in the share box. Here's how it looks

![image](https://f.cloud.github.com/assets/977460/2331791/c4e610a8-a44e-11e3-860c-423f2548ac74.png)

is there some additional configurations i have to place before facebook could read my meteor app? 

Do you encounter the same problems?

**Comment by hugesuccess** [comment]
Yeah integration w/ meta tags is tricky. Meteor doesn't provide dynamic meta tags (to my knowledge), and manipulating them via javascript is sketchy, particularly w/ spiders/crawlers/ etx. If you want to add extra data to your dialog, use javascript over the handlebars helpers. From the documentation:

```
FB.ui(
      {
       method: 'feed',
       name: 'The Facebook SDK for Javascript',
       caption: 'Bringing Facebook to the desktop and mobile web',
       description: (
          'A small JavaScript library that allows you to harness ' +
          'the power of Facebook, bringing the user\'s identity, ' +
          'social graph and distribution power to your site.'
       ),
       link: 'https://developers.facebook.com/docs/reference/javascript/',
       picture: 'http://www.fbrell.com/public/f8.jpg'
      },
      function(response) {
        if (response && response.post_id) {
          alert('Post was published.');
        } else {
          alert('Post was not published.');
        }
      }
    );

```

For more info check out https://developers.facebook.com/docs/javascript/quickstart

**Comment by geekyme** [comment]
great tip! working on meteor too long makes me lazy i guess... :P forgot that I can use the FB api directly. now my shared stories looks beautiful THANK YOU!
