### ISSUE TITLE
No more handlebars as of 0.8.0

### ISSUE THREAD

**Issue by geekyme** [hugesuccess/facebook-sdk#5]
hello just sounding out that this package breaks as of meteor 0.8.0. handlebars is removed.

**Comment by hugesuccess** [comment]
What do you think? Spacebars helpers? I really like the idea of handlebars/spacebars/jade helpers -- like the login buttons --, but IDK if anybody uses them or how much value they have. :/

**Comment by geekyme** [comment]
I like the helpers. We should keep them. Change them to use the new space bars / blaze syntax (UI.registerHelper)

**Comment by geekyme** [comment]
#6

**Comment by geekyme** [comment]
Just made a pull request to support blaze helpers. HTML ones only though. Not jade. Lets track the issue there.

**Comment by hugesuccess** [comment]
Wondering if we should add the less than sign (>). For example {{loginButtons}} is now {{> loginButtons}} and {{yield}} is now {{> yield}}. Sweet pull btw I'll add Jade support this weekend.

**Comment by geekyme** [comment]
Oh yeah actually that's a better idea. I think the current style is to use helpers {{}} when generating attribute or text and using > when we wanna include HTML blocks (like the Facebook likes and shares)
