### ISSUE TITLE
File not found: helpers.js

### ISSUE THREAD

**Issue by rickstar8** [hugesuccess/facebook-sdk#7]
Hey, I removed this package and then I tried adding it again to the app and now I'm getting an error when I 'mrt add', I get the following error:

=> Errors while scanning packages:
While building package `facebook-sdk`: 
error: File not found: helpers.js

**Comment by hugesuccess** [comment]
Umm that's bad! helpers.js was where all the Handlebars template helpers where. But they all got deleted with the new SpaceBars template engine. I published an updated package, it's installing fine for me. Check it out and let me know if it's working for you.

**Comment by rickstar8** [comment]
I just tried reinstalling it again and it works now, thanks for your help!

**Comment by hugesuccess** [comment]
: )
